### ISSUE TITLE
Create the ERD

### ISSUE THREAD

**Issue by tborsa** [alumni-lab/dave-s-netflix#1]
Use the user stories in the [Plannification](https://github.com/alumni-lab/dave-s-netflix/projects/1) project for this repo, to plan out and create a first draft for the projects ERD. 

When you have done so add the ERD image/pdf/whatever to the [project](https://github.com/alumni-lab/dave-s-netflix/projects/1) as a note and comment on this issue that you have done so.

**Comment by benjdelt** [comment]
I added a link in the project to the ERD that we reviewed together last week.
