### ISSUE TITLE
Create the Wireframes

### ISSUE THREAD

**Issue by tborsa** [alumni-lab/dave-s-netflix#2]
Use the user stories in the [Plannification](https://github.com/alumni-lab/dave-s-netflix/projects/1) project for this repo, to plan out and create a the wireframes for this project. 

When you have done so add the Wireframe images/pdf/whatever to the [project](https://github.com/alumni-lab/dave-s-netflix/projects/1) as a note and comment on this issue that you have done so.

**Comment by benjdelt** [comment]
I've pushed them in the [project folder](https://github.com/alumni-lab/dave-s-netflix/tree/master/project/wireframes)
